inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - test/services/mailgun_service_test.rb 
    - test/services/mailtester_service.rb # hash to big in test file switch to VCR gem
