version: '2'

services:
  db:
    image: postgres:9.6.1
    ports:
      - 5432:5432
  app:
    build: 
      context: .
      dockerfile: docker/rails/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - gems
      - spring
    volumes_from:
      - gems
    environment:
      - GEM_PATH=/ruby_gems
      - GEM_HOME=/ruby_gems
  spring:
    build: 
      context: .
      dockerfile: docker/rails/Dockerfile
    command: bundle exec spring server
    volumes:
      - .:/usr/src/app
    depends_on:
      - gems
    volumes_from:
      - gems
    environment:
      - GEM_PATH=/ruby_gems
      - GEM_HOME=/ruby_gems
  gems:
    image: busybox
    command: tail -f /dev/null
    volumes:
      - /ruby_gems
  redis:
    image: redis
  sidekiq:
    build: 
      context: .
      dockerfile: docker/rails/Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - gems
    volumes_from:
      - gems
    command: bundle exec sidekiq -c 5
    environment:
      - GEM_PATH=/ruby_gems
      - GEM_HOME=/ruby_gems
  ngrok:
    tty: true
    build: 
      context: docker/ngrok
      dockerfile: Dockerfile
    ports:
      - 4040:4040
