# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f7c45495102f345ed4cf5fa6035e232c51691d3e1cfff601eabb941f9944e626cca4a0cf366749720be14eb5aa1e69c7dca1b4864e45056e3259a7a0e0a5c4

test:
  secret_key_base: c5b3b80e7cfefdf2b014ae687253b1f5fb744d40d15479706fea00b1fc83ff057bf77fe01d6142dd1007742d18d96b63f1134eb1ee4314dfe634bad8197d50d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8fc66e668e210bfe0d79d4b6bbcb644304df5a85f16c915503588c440309e6c564467b042abe2c188b2e171c510d06824ce25d7f9a29febeab6ba44a8573e36f
